# ME-ICA Docker image
#
# This Dockerfile intentionally uses the same release installer path as a normal
# user installation.  The installer clones the matched me-ica-X.Y.Z source tree,
# creates the dedicated micromamba environment, and downloads the matched
# distributed AFNI runtime into:
#
#   /opt/meica/me-ica-X.Y.Z/meica-afni-runtime/
#
# The container entrypoint then sources the activation helper created by
# install.sh.  This keeps Docker aligned with the documented install behavior:
# meica.py is available, the runtime utils directory is on PATH for tools such
# as dcm2niix, and the full AFNI runtime/bin directory is activated internally
# by meica.py and generated _meica_*.sh scripts rather than exposed globally.

FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
ARG MEICA_VERSION=4.0.1
ARG INSTALLDIR=/opt/meica

ENV MEICA_VERSION=${MEICA_VERSION}
ENV MEICA_HOME=${INSTALLDIR}
ENV MEICA_ACTIVATE=/root/activate_meica

# Minimal system requirements for the installer and for routine container use.
# AFNI is not installed with apt/conda here; it is supplied by the ME-ICA
# distributed runtime downloaded by install.sh on Linux.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        bzip2 \
        ca-certificates \
        coreutils \
        curl \
        git \
        gzip \
        tar \
        tcsh \
    && rm -rf /var/lib/apt/lists/*

# Canonical ME-ICA installation path: use the release installer exactly as a
# user would, with INSTALLDIR set to /opt/meica inside the image.
RUN curl -fsSL "https://raw.githubusercontent.com/ME-ICA/me-ica/${MEICA_VERSION}/install.sh" \
    | bash -s -- "${INSTALLDIR}"

# Source the activation helper generated by install.sh, then run the requested
# command.  If the user supplies options beginning with '-', treat them as
# meica.py options.
RUN cat > /usr/local/bin/meica-docker-entrypoint <<'EOF_ENTRYPOINT' \
    && chmod +x /usr/local/bin/meica-docker-entrypoint
#!/usr/bin/env bash
set -euo pipefail

: "${MEICA_ACTIVATE:=/root/activate_meica}"

if [ ! -f "${MEICA_ACTIVATE}" ]; then
    echo "ERROR: ME-ICA activation helper not found: ${MEICA_ACTIVATE}" >&2
    exit 1
fi

# Use the same activation source that users get from install.sh.  This activates
# micromamba, exposes meica.py, and exposes runtime/utils for dcm2niix.  The
# full AFNI runtime/bin remains internal to meica.py/runtime.py.
source "${MEICA_ACTIVATE}"

if [ "$#" -eq 0 ]; then
    set -- meica.py -h
elif [[ "$1" == -* ]]; then
    set -- meica.py "$@"
fi

exec "$@"
EOF_ENTRYPOINT

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/meica-docker-entrypoint"]
CMD ["meica.py", "-h"]
